version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    environment:
      - LANGFLOW_DATABASE_URL=postgres://postgres:R14V1ATysmZ4Mptzh3SmeKvoVqY6CegJfqJ0JptuUlmSY36z4bL7e2WmL9JiMTnY@74.208.237.199:5433/langflow
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow

volumes:
  langflow-data:
