version: "3.8"

services:
  langflow:
    image: langflowai/langflow:latest # or another version tag on https://hub.docker.com/r/langflowai/langflow 
    pull_policy: always               # set to 'always' when using 'latest' image
    ports:
      - "7860:7860"
    depends_on:
      - postgres
    environment:
      - LANGFLOW_DATABASE_URL=postgres://postgres:q2VrkP10fsRYWd4jO0wfO8wUF2JfYtSOQlOaNs2bL3HWmf5uBKDLOyFYDmnFd6XQ@74.208.237.199:5432/postgres
      # This variable defines where the logs, file storage, monitor data and secret keys are stored.
    volumes:
      - langflow-data:/app/langflow

volumes:
  langflow-data:
